platform:
  - Win32
environment:
  PYTHON: "C:\\Python35"
  APPVEYOR_RDP_PASSWORD: 2FXhItUvIXVeV9pYVmzs

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off
install:
  - powershell -command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.bat -OutFile %TEMP%/install-zpm.bat;" && %TEMP%/install-zpm.bat 
  - "SET PATH=%PATH%;%USERPROFILE%/zpm/bin"
test_script:
  - cd test && zpm run test-definition GainInput
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
